budget:

  enabled: true

  currency: USD

  default:
    daily: 2.00
    monthly: 30.00

  tiers:

    premium:
      enabled: true
      enforce_budget: true

    paid:
      enabled: true
      enforce_budget: true

    free:
      enabled: true
      enforce_budget: false

    local:
      enabled: true
      enforce_budget: false

  behavior:
    on_budget_exceeded: fallback
